I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\214542\\Desktop\\renpy-8.0.3-sdk\\Lacuna\\game\\saves\\navigation.json.new' -> 'C:\\Users\\214542\\Desktop\\renpy-8.0.3-sdk\\Lacuna\\game\\saves\\navigation.json'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\214542\Desktop\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\214542\Desktop\renpy-8.0.3-sdk\renpy\main.py", line 610, in main
    renpy.dump.dump(False)
  File "C:\Users\214542\Desktop\renpy-8.0.3-sdk\renpy\dump.py", line 262, in dump
    os.rename(new, filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\214542\\Desktop\\renpy-8.0.3-sdk\\Lacuna\\game\\saves\\navigation.json.new' -> 'C:\\Users\\214542\\Desktop\\renpy-8.0.3-sdk\\Lacuna\\game\\saves\\navigation.json'

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Lacuna. 0.81
Wed May  3 23:19:51 2023
