I'm sorry, but an uncaught exception occurred.

After loading the script.
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\214542\\Desktop\\renpy-8.0.3-sdk\\Lacuna\\game\\saves\\navigation.json.new' -> 'C:\\Users\\214542\\Desktop\\renpy-8.0.3-sdk\\Lacuna\\game\\saves\\navigation.json'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\214542\Desktop\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\214542\Desktop\renpy-8.0.3-sdk\renpy\main.py", line 548, in main
    if renpy.parser.report_parse_errors():
  File "C:\Users\214542\Desktop\renpy-8.0.3-sdk\renpy\parser.py", line 3109, in report_parse_errors
    renpy.display.error.report_parse_errors(full_text, error_fn)
  File "C:\Users\214542\Desktop\renpy-8.0.3-sdk\renpy\display\error.py", line 174, in report_parse_errors
    error_dump()
  File "C:\Users\214542\Desktop\renpy-8.0.3-sdk\renpy\display\error.py", line 86, in error_dump
    renpy.dump.dump(True)
  File "C:\Users\214542\Desktop\renpy-8.0.3-sdk\renpy\dump.py", line 262, in dump
    os.rename(new, filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\214542\\Desktop\\renpy-8.0.3-sdk\\Lacuna\\game\\saves\\navigation.json.new' -> 'C:\\Users\\214542\\Desktop\\renpy-8.0.3-sdk\\Lacuna\\game\\saves\\navigation.json'

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Lacuna. 0.81
Thu May  4 14:08:34 2023
