I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 6076, in script
    T "Something's wrong. I think we need to run."
Exception: Sayer 'T' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 6076, in script
    T "Something's wrong. I think we need to run."
  File "renpy/ast.py", line 680, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'T' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
The Thief, the Toad, the Witch & the Mushroom. 1.0
Tue Nov 14 18:23:18 2023
