I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2745, in script
    my "Sorry, uh - Ho! Young Traveller!"
Exception: Sayer 'my' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2745, in script
    my "Sorry, uh - Ho! Young Traveller!"
  File "D:\ThiefWitchToadMushroom\renpy-8.2.0-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "D:\ThiefWitchToadMushroom\renpy-8.2.0-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\ThiefWitchToadMushroom\renpy-8.2.0-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'my' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
The Wolf. 1.0
Thu Mar  7 16:10:15 2024
